version: "3.9"

services:
  app:
    image: boegynat/getting-started:latest
    container_name: app
    ports:
      - "3000:3000"

  backend:
    image: bokey_backend:1.0
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - backend-networks
    volumes:
      - .:/code
    depends_on:
      - db
#   db:
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres

# networks:
#   default:
#     driver: bridge
#   backend-networks:
#     driver: bridge
#   frontend-networks:
#     driver: bridge

# volumes:
#   postgres_data:
#     driver: local
