const Caterings = [
    {
        id: 1,
        requesterId: 2,
        type: "จัดเลี้ยงให้นักศึกษาฝึกงาน",
        startDate: new Date(),
        startTime: new Date(),
        endTime: new Date(),
        location: "SCG อาคาร 100 ปี",
        numberParticipant: 10,
        status: "pending",
        createdAt: new Date(),
        updatedAt: new Date(),
        approverId: 1,
        approvedAt: new Date(),
    },
    {
        id: 2,
        requesterId: 5,
        type: "จัดเลี้ยงให้นักศึกษาฝึกงาน",
        startDate: new Date(),
        startTime: new Date(),
        endTime: new Date(),
        location: "SCG อาคาร 100 ปี",
        numberParticipant: 14,
        status: "pending",
        createdAt: new Date(),
        updatedAt: new Date(),
        approverId: 1,
        approvedAt: new Date(),
    },
    {
        id: 3,
        requesterId: 10,
        type: "จัดเลี้ยงให้นักศึกษาฝึกงาน",
        startDate: new Date(),
        startTime: new Date(),
        endTime: new Date(),
        location: "SCG อาคาร 100 ปี",
        numberParticipant: 14,
        status: "pending",
        createdAt: new Date(),
        updatedAt: new Date(),
        approverId: 1,
        approvedAt: new Date(),
    },
]

module.exports = Caterings;