const Maintenances = [
	{
		id: 1,
		userId: 1,
		maintenanceType: 1,
		requestorName: "หน่องมน คนบ้านเดียวกัน",
		phoneNumber: "0999999999",
		email: "nongmon@gmail.com",
		company: "SCG",
		agency: "HR",
		costCenter: 1,
		costElement: 2,
		location: "ตึกใบหยก",
		locationDetail: "ชั้น 36",
		startDate: new Date(),
		attachment: [
			{
				filename: "1636633905764_unknow.pdf",
				size: 2120996,
				path: `file/maintenance/1/1636633905764_unknow.pdf`
			},
			{
				filename: "1636633905765_unknow.jpg",
				size: 2120996,
				path: `file/maintenance/1/1636633905765_unknow.jpg`
			}
		],
		description: "หลอดไฟเสียที่ห้อง 3610",
		status: 4, //1 = wait, 2 = inprogress, 3 = complete, 4 = reject, 5 = cancel
		progress: 0,
		technicianId: [],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 2,
		userId: 1,
		maintenanceType: 2,
		requestorName: "หน่องมน คนบ้านเดียวกัน",
		phoneNumber: "0999999999",
		email: "nongmon@gmail.com",
		company: "SCG",
		agency: "HR",
		costCenter: 1,
		costElement: 2,
		location: "ตึกใบหยก",
		locationDetail: "ชั้น 36",
		startDate: new Date(),
		attachment: [],
		description: "หลอดไฟเสียที่ห้อง 3610",
		status: 3,
		progress: 100,
		technicianId: [1],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 3,
		userId: 1,
		maintenanceType: 3,
		requestorName: "หน่องมน คนบ้านเดียวกัน",
		phoneNumber: "0999999999",
		email: "nongmon@gmail.com",
		company: "SCG",
		agency: "HR",
		costCenter: 1,
		costElement: 2,
		location: "ตึกใบหยก",
		locationDetail: "ชั้น 36",
		startDate: new Date(),
		attachment: [],
		description: "หลอดไฟเสียที่ห้อง 3610",
		status: 2,
		progress: 0,
		technicianId: [1],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 4,
		userId: 1,
		maintenanceType: 3,
		requestorName: "หน่องมน คนบ้านเดียวกัน",
		phoneNumber: "0999999999",
		email: "nongmon@gmail.com",
		company: "SCG",
		agency: "HR",
		costCenter: 1,
		costElement: 2,
		location: "ตึกใบหยก",
		locationDetail: "ชั้น 36",
		startDate: new Date(),
		attachment: [],
		description: "หลอดไฟเสียที่ห้อง 3610",
		status: 1,
		progress: 0,
		technicianId: [],
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 5,
		userId: 1,
		maintenanceType: 3,
		requestorName: "หน่องมน คนบ้านเดียวกัน",
		phoneNumber: "0999999999",
		email: "nongmon@gmail.com",
		company: "SCG",
		agency: "HR",
		costCenter: 1,
		costElement: 2,
		location: "ตึกใบหยก",
		locationDetail: "ชั้น 36",
		startDate: new Date(),
		attachment: [],
		description: "หลอดไฟเสียที่ห้อง 3610",
		status: 1,
		progress: 0,
		technicianId: [],
		createdAt: new Date(),
		updatedAt: new Date(),
	},

]

module.exports = Maintenances;