const AdminLentCars = [
    {
        id:1,
        item:1,
        complete:10,
        newHost:3,
        newUser:10,
        month:"2021-08-31",
    },
    {
        id:2,
        item:2,
        complete:12,
        newHost:3,
        newUser:10,
        month:"2021-09-31",
    },
    {
        id:3,
        item:3,
        complete:16,
        newHost:3,
        newUser:10,
        month:"2021-10-31",
    },
    {
        id:4,
        item:4,
        complete:22,
        newHost:3,
        newUser:10,
        month:"2021-11-31",
    },
    {
        id:5,
        item:5,
        complete:30,
        newHost:3,
        newUser:10,
        month:"2021-12-31",
    },
];

module.exports = AdminLentCars;