const BetweenSiteCars = [
    {
        id:1,
        idUser:2,
        gettingPlace:"Site 1",
        spotGettingPlace:"หน้าโรงงาน",
        toPlace:"Site 3",
        spotToPlace:"werehouse",
        idDriverRouteDay:null,
        arrivedTime:null,
        isFinish:false,
    },
    {
        id:2,
        idUser:5,
        gettingPlace:"Site 3",
        spotGettingPlace:"werehouse",
        toPlace:"Site 7",
        spotToPlace:"หน้าป้อมยาม",
        idDriverRouteDay:null,
        arrivedTime:null,
        isFinish:false,
    },
    {
        id:3,
        idUser:10,
        gettingPlace:"Site 7",
        spotGettingPlace:"หน้าป้อมยาม",
        toPlace:"Site 1",
        spotToPlace:"หน้าโรงงาน",
        idDriverRouteDay:null,
        arrivedTime:null,
        isFinish:false,
    },
    {
        id:4,
        idUser:1,
        gettingPlace:"Site 1",
        spotGettingPlace:"หน้าโรงงาน",
        toPlace:"Site 3",
        spotToPlace:"werehouse",
        idDriverRouteDay:3,
        arrivedTime:"2022-02-12 10:30",
        isFinish:false,
    },
];

module.exports = BetweenSiteCars;