const Buses = [
    {
        id: 1,
        licensePlate: "กก 1234",
        type: "รถบัส",
        business: "บริษัท เพาเวอร์เซ็นเตอร์ เซอร์วิส(1999) จำกัด",
        rentalDate: "01/03/2020",
        expirationDate: "14/07/2021",
        imagename: "bus1.jpg",
    },
    {
        id: 2,
        licensePlate: "นฟ 3751",
        type: "รถตู้",
        business: "บริษัท ห้างหุ้นส่วนจำกัด",
        rentalDate: "01/01/2020",
        expirationDate: "31/12/2021",
        imagename: "bus2.png",
    },
    {
        id: 3,
        licensePlate: "บส 9078",
        type: "รถตู้",
        business: "บริษัท ส.สุขสมโภชน์ คาร์เซอร์วิส",
        rentalDate: "01/06/2020",
        expirationDate: "9/05/2022",
        imagename: "bus3.jpg",
    },
    {
        id: 4,
        licensePlate: "ดป 7638",
        type: "รถบัส",
        business: "บริษัท เพาเวอร์เซ็นเตอร์ เซอร์วิส(1999) จำกัด",
        rentalDate: "01/03/2020",
        expirationDate: "14/07/2021",
        imagename: "bus1.jpg",
    },
    {
        id: 5,
        licensePlate: "ฟพ 5007",
        type: "รถตู้",
        business: "บริษัท ห้างหุ้นส่วนจำกัด",
        rentalDate: "01/01/2020",
        expirationDate: "31/12/2021",
        imagename: "bus2.png",
    },
    {
        id: 6,
        licensePlate: "พน 4795",
        type: "รถตู้",
        business: "บริษัท ส.สุขสมโภชน์ คาร์เซอร์วิส",
        rentalDate: "01/06/2020",
        expirationDate: "9/05/2022",
        imagename: "bus3.jpg",
    },
    {
        id: 7,
        licensePlate: "ผพ 2864",
        type: "รถบัส",
        business: "บริษัท เพาเวอร์เซ็นเตอร์ เซอร์วิส(1999) จำกัด",
        rentalDate: "01/03/2020",
        expirationDate: "14/07/2021",
        imagename: "bus1.jpg",
    },
    {
        id: 8,
        licensePlate: "ฑณ 1423",
        type: "รถตู้",
        business: "บริษัท ห้างหุ้นส่วนจำกัด",
        rentalDate: "01/01/2020",
        expirationDate: "31/12/2021",
        imagename: "bus2.png",
    },
    {
        id: 9,
        licensePlate: "มส 3054",
        type: "รถตู้",
        business: "บริษัท ส.สุขสมโภชน์ คาร์เซอร์วิส",
        rentalDate: "01/06/2020",
        expirationDate: "9/05/2022",
        imagename: "bus3.jpg",
    },

]

module.exports = Buses;