const Cars = [
    {
        id: 1,
        licensePlate: "พด 3875",
        type: "รถเก๋ง",
        brand: "Suzuki",
        model: "Suzuki Celerio",
        motor: "998 cc",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถข้ามจังหวัด",
        maxSeats: 4,
        imagename: "car1.png",
    },
    {
        id: 2,
        licensePlate: "กย 1515",
        type: "รถกระบะ",
        brand: "Toyota",
        model: "Toyota Hilux Revo 2017",
        motor: "2,393 cc, 150 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถรับส่งของ",
        maxSeats: 4,
        imagename: "car2.png",
    },
    {
        id: 3,
        licensePlate: "พร 7450",
        type: "รถเก๋ง",
        brand: "Nissan",
        model: "Nissan March",
        motor: "1,198 cc, 79 แรงม้า(PS)",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถในพื้นที่",
        maxSeats: 4,
        imagename: "car3.jpg",
    },
    {
        id: 4,
        licensePlate: "ธฑ 8430",
        type: "รถตู้",
        brand: "Nissan",
        model: "Nissan Urvan",
        motor: "2,488 cc, 129 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "ไม่มี",
        capacity: 6,
        purpose: "รถข้ามจังหวัด",
        maxSeats: 16,
        imagename: "car4.jpg",
    },
    {
        id: 5,
        licensePlate: "กฏ 8032",
        type: "รถเก๋ง",
        brand: "Honda",
        model: "Honda Brio",
        motor: "1,200 cc",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถข้ามจังหวัด",
        maxSeats: 4,
        imagename: "car5.jpg",
    },
    {
        id: 6,
        licensePlate: "อฮ 2803",
        type: "รถกระบะ",
        brand: "Toyota",
        model: "Toyota Hilux Revo 2017",
        motor: "2,393 cc, 150 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถรับส่งของ",
        maxSeats: 4,
        imagename: "car2.png",
    },
    {
        id: 7,
        licensePlate: "ทม 2940",
        type: "รถเก๋ง",
        brand: "Nissan",
        model: "Nissan March",
        motor: "1,198 cc, 79 แรงม้า(PS)",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถเข้าพื้นที่",
        maxSeats: 4,
        imagename: "car3.jpg",
    },
    {
        id: 8,
        licensePlate: "บล 1023",
        type: "รถเก๋ง",
        brand: "Suzuki",
        model: "Suzuki Celerio",
        motor: "998 cc",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        purpose: "รถข้ามจังหวัด",
        maxSeats: 4,
        imagename: "car1.png",
    },
    {
        id: 9,
        licensePlate: "ปฟ 2538",
        type: "รถตู้",
        brand: "Nissan",
        model: "Nissan Urvan",
        motor: "2,488 cc, 129 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "มี",
        capacity: 6,
        purpose: "รถข้ามจังหวัด",
        maxSeats: 16,
        imagename: "car4.jpg",
    },
]

module.exports = Cars;