const CrossAreaCarBookings = [
    {
        id:1,
        idUser:1,
        name:"นาย สมพงษ์ วาทศิลดี",
        telephoneMobile:"0843245543",
        email:"Som_Pong@fmail.com",
        flight:"oneWay",
        fromPlace:"site 1",
        toPlace:"บางซื่อ",
        numberOfPassenger:2,
        departureDate:"2022-05-30",
        startTime:"2021-03-12 08:00:00",
        endTime:"2021-03-12 20:00:00",
        fromPlaceReturn:null,
        toPlaceReturn:null,
        numberOfPassengerReturn:0,
        returnDate:null,
        returnStartTime:null,
        returnEndTime:null,
        purpose:"ประชุม",
        idTypeCar:2,
        idVehicleBrandAndModel:1,
        capacity:4,
        gettingPoint: "manyPoint",
        idApprovedUser:2,
        nameApproved: "Theodor O'Moore",
        departmentApproved: "HR Business Partner",
        companyApproved: "Thai Polyethylene Co., Ltd.",
        statusApproved: false,
        Approved:false,
        statusManageCar: false,
        plate_No:null,
        nameDriver:null,
        note:null
    },
    {
        id:2,
        idUser:30,
        name:"นาย ประสงค์  หาญจิระสวัสดิ์",
        telephoneMobile:"0992431238",
        email:"s@s.com",
        flight:"twoWay",
        fromPlace:"site 1",
        toPlace:"บางซื่อ",
        numberOfPassenger:1,
        departureDate:"2022-05-30",
        startTime:"2021-03-12 06:00:00",
        endTime:"2021-03-12 22:00:00",
        fromPlaceReturn:"บางซื่อ",
        toPlaceReturn:"site 1",
        numberOfPassengerReturn:1,
        returnDate:"Mon Feb 28 2022 10:58:29 GMT+0700 (Indochina Time)",
        returnStartTime:"2021-03-12 04:00:00",
        returnEndTime:"2021-03-12 23:00:00",
        purpose:"ประชุม",
        idTypeCar:2,
        idVehicleBrandAndModel:1,
        capacity:4,
        gettingPoint: "onePoint",
        idApprovedUser:2,
        nameApproved: "Theodor O'Moore",
        departmentApproved: "HR Business Partner",
        companyApproved: "Thai Polyethylene Co., Ltd.",
        statusApproved: false,
        Approved:false,
        statusManageCar: false,
        plate_No:null,
        nameDriver:null,
        note:null
    },
];

module.exports = CrossAreaCarBookings;