const Employees = [
    {
        idUser:2036,
        scgEmployeeId:"0100-000680",
        prename:"นาย",
        fNameThai: "สุวัฒ ป้อมภา",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        username:"",
        email: "krystich@domain.com",
        password:"",
        authorities:["ROLE_USER"],
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.681240612897026,
        long:101.22069543253524,
        status:0,
        image:"1.jpg",
        pointFriendToFriend:4.5,
        pointLentCar:4.5,
    },
    {
        idUser:2044,
        scgEmployeeId:"0100-001064",
        prename:"นาย",
        fNameThai: "สมบูรณ์ ไทยญานุสร",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.780292135351459,
        long:101.19022439116034,
        status:1,
        image:"2.jpg"
    },
    {
        idUser:2073,
        scgEmployeeId:"0100-001605",
        prename:"นาย",
        fNameThai: "ศักดิ์ชัย หุมสิน",
        AgeYear:29,
        AgeMonth:10,
        AgeWorkingYear:5,
        AgeWorkingMonth:2,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.682209355620243,
        long:101.24201258509072,
        status:1,
        image:"3.jpg"
    },
    {
        idUser:2079,
        scgEmployeeId:"0100-001415",
        prename:"นาย",
        fNameThai: "ศักดิ์ชัย หุมสิน",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.716237833669975,
        long:101.30725134245453,
        status:0,
        image:"4.jpg"
    },
    {
        idUser:2090,
        scgEmployeeId:"0100-001571",
        prename:"นาย",
        fNameThai: "ภูมิมินทร์ ใจหาญ",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.6868052,
        long:101.2651274,
        status:0,
        image:"5.jpg"
    },
    {
        idUser:2092,
        scgEmployeeId:"0100-001374",
        prename:"นาย",
        fNameThai: "สัมฤทธิ์ คำสงค์",
        AgeYear:29,
        AgeMonth:10,
        AgeWorkingYear:5,
        AgeWorkingMonth:2,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.767028760158432,
        long:101.17723029020047,
        status:0,
        image:"6.jpg"
    },
    {
        idUser:2099,
        scgEmployeeId:"0100-000960",
        prename:"นาย",
        fNameThai: "ชูชาติ รัตนเพ็ชร",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        email: "chuchara@scg.com",
        mobileNumber: "0890589785",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE - Rayong Site#1 @12.700017,101.134783",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"19/21",
        villageSoi:"หมู่1/หมูบ้านสกาย วิลล์ / ซอย 4.",
        streetRoad:"ชากใหญ่-บ้านแลง",
        subdistrictTambol:"นาตาขวัญ",
        district:"เมือง",
        province:"ระยอง",
        postalCode:"21000",
        lat:12.695161966150467,
        long:101.31651283724382,
        status:0,
        image:"7.jpg"
    },
    {
        idUser:2114,
        scgEmployeeId:"0100-001540",
        prename:"นาย",
        fNameThai: "สัมฤทธิ์ คำสงค์",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.712475559716722,
        long:101.21318225570424,
        status:0,
        image:"8.jpg"
    },
    {
        idUser:2118,
        scgEmployeeId:"0100-001478",
        prename:"นาย",
        fNameThai: "อภิวัฒน์ นิคมเขตต์",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "apiwatni@scg.com",
        mobileNumber: "0851019031",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE - Rayong Site#1 @12.700017,101.134783",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"69/8",
        villageSoi:"หมู่ 8 บ้านสะพานหิน-เขาโบสถ์",
        streetRoad:"-",
        subdistrictTambol:"ทับมา",
        district:"เมือง",
        province:"ระยอง",
        postalCode:"21000",
        lat:12.72518242027518,
        long:101.22013902425918,
        status:0,
        image:"9.jpg"
    },
    {
        idUser:2145,
        scgEmployeeId:"0100-001257",
        prename:"นาย",
        fNameThai: "ณัฐพล พรพิทยากุล",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.712218399999999,
        long:101.32196980000001,
        status:0,
        image:"10.jpg"
    },
    {
        idUser:2148,
        scgEmployeeId:"0100-001775",
        prename:"นาย",
        fNameThai: "ภานุวัฒน์ แก้ววงศ์",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.6736612,
        long:101.27238060000001,
        status:0,
        image:"11.jpg"
    },
    {
        idUser:2167,
        scgEmployeeId:"0100-001572",
        prename:"นาย",
        fNameThai: "ณัฐพล พรพิทยากุล",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.679503591987821,
        long:101.27955072364304,
        status:0,
        image:"12.jpg"
    },
    {
        idUser:2168,
        scgEmployeeId:"0100-001791",
        prename:"นาย",
        fNameThai: "ภานุวัฒน์ แก้ววงศ์",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.676568561067688,
        long:101.26440310014563,
        status:0,
        image:"13.jpg"
    },
    {
        idUser:2180,
        scgEmployeeId:"0100-001133",
        prename:"นาย",
        fNameThai: "ชนาธิป สรรพวิเศษ",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.709720017704441,
        long:101.21109330649875,
        status:0,
        image:"14.jpg"
    },
    {
        idUser:2188,
        scgEmployeeId:"2220-000019",
        prename:"นาย",
        fNameThai: "สนิท แต่งตั้ง",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.696188862837351,
        long:101.21798775039829,
        status:0,
        image:"15.jpg"
    },
    {
        idUser:2190,
        scgEmployeeId:"0100-001381",
        prename:"นาย",
        fNameThai: "จีรศักดิ์ ประสพสุข",
        AgeYear:28,
        AgeMonth:1,
        AgeWorkingYear:4,
        AgeWorkingMonth:5,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.766356102876506,
        long:101.17707017835976,
        status:0,
        image:"16.jpg"
    },
    {
        idUser:2191,
        scgEmployeeId:"2220-000034",
        prename:"นาย",
        fNameThai: "จีรศักดิ์ ประสพสุข",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "krystich@domain.com",
        mobileNumber: "085-550-0949",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"12",
        villageSoi:"",
        streetRoad:"เอกมัย",
        subdistrictTambol:"คลองเตย",
        district:"คลองเตย",
        province:"กรุงเทพมหานคร",
        postalCode:"10150",
        lat:12.847289731643839,
        long:101.19282620433572,
        status:0,
        image:"17.jpg"
    },
    {
        idUser:2213,
        scgEmployeeId:"0100-001154",
        prename:"นาง",
        fNameThai: "จิรพันธ์ สุวรรณทวี",
        AgeYear:31,
        AgeMonth:3,
        AgeWorkingYear:6,
        AgeWorkingMonth:1,
        email: "jirapans@scg.com",
        mobileNumber: "0849660533",
        position: "Assistant Manager-HR",
        departmentName: "HR Business Partner",
        departmentShortName: "HRBP",
        workingLocation: "TPE - Rayong Site#1 @12.700017,101.134783",
        companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
        addressNumber:"44/112",
        villageSoi:"ศักดิ์ทิพย์8",
        streetRoad:"กรอกยายชา",
        subdistrictTambol:"เนินพระ",
        district:"เมือง",
        province:"ระยอง",
        postalCode:"21150",
        lat:12.679434938663885,
        long:101.17404131169592,
        status:0,
        image:"18.jpg"
    },
    {
        idUser:2221,
        fNameThai: "DEPORT Site 1",
        departmentName: "",
        lat:12.6999465,
        long:101.1347889,
    },
]

module.exports = Employees;