const PassengerFriendToFriends = [
    {
        id:1,
        idRegister:1,
        idUser:7,
        startDate:"2022-02-05",
        endDate:"2022-02-08",
        status:true,
        joined:true,
    },
    {
        id:2,
        idRegister:1,
        idUser:9,
        startDate:"2022-02-05",
        endDate:"2022-02-05",
        status:false,
        joined:false,
    },
    {
        id:3,
        idRegister:3,
        idUser:1,
        startDate:"2022-02-05",
        endDate:"2022-02-07",
        status:true,
        joined:true,
    },
    {
        id:4,
        idRegister:5,
        idUser:1,
        startDate:"2022-02-20",
        endDate:"2022-02-20",
        status:false,
        joined:false,
    },
];

module.exports = PassengerFriendToFriends;