const RegisterOfDriver = [
    {
        id:1,
        type:"GoToWork",
        idUser:1,
        name:"นาย สมชาย ปราศรัยดี",
        phoneNumber:"084-2413-1754",
        fromPlace:"ดีคอนโดระยอง",
        toPlace:"site 1",
        seats:3,
        numberOfPassenger:1,
        availableSeats:2,
        startDate:"2022-02-5",
        endDate:"2022-02-9",
        time:new Date(),
        detail:"จุดขึ้นรถ : หน้าตึกดีคอนโดระยอง รถ honda สีแดง ทะเบียน หก 6073",
        createDate:"2022-01-10"
    },
    {
        id:2,
        type:"ComeBackHome",
        idUser:3,
        name:"นาย สมหมาย ปลายแสงสว่าง",
        phoneNumber:"084-2413-1754",
        fromPlace:"site 1",
        toPlace:"ดีคอนโดระยอง",
        seats:2,
        numberOfPassenger:1,
        availableSeats:1,
        startDate:new Date().setDate(5),
        endDate:new Date().setDate(20),
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:3,
        type:"GoToWork",
        idUser:4,
        name:"นาย กรพงษ์ กล้าหาญ",
        phoneNumber:"084-2413-1754",
        fromPlace:"ดีคอนโดระยอง",
        toPlace:"site 1",
        seats:3,
        numberOfPassenger:1,
        availableSeats:2,
        startDate:"2022-02-5",
        endDate:"2022-02-7",
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:4,
        type:"ComeBackHome",
        idUser:1,
        name:"นาย สมชาย ปราศรัยดี",
        phoneNumber:"084-2413-1754",
        fromPlace:"site 1",
        toPlace:"ดีคอนโดระยอง",
        seats:3,
        numberOfPassenger:0,
        availableSeats:3,
        startDate:"2022-02-5",
        endDate:"2022-02-9",
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:5,
        type:"GoToWork",
        idUser:3,
        name:"นาย สมหมาย ปลายแสงสว่าง",
        phoneNumber:"084-2413-1754",
        fromPlace:"ดีคอนโดระยอง",
        toPlace:"site 1",
        seats:2,
        numberOfPassenger:1,
        availableSeats:1,
        startDate:"2022-02-20",
        endDate:"2022-02-20",
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:6,
        type:"ComeBackHome",
        idUser:4,
        name:"นาย กรพงษ์ กล้าหาญ",
        phoneNumber:"084-2413-1754",
        fromPlace:"site 7",
        toPlace:"ดีคอนโดระยอง",
        seats:3,
        numberOfPassenger:1,
        availableSeats:2,
        startDate:"2022-02-20",
        endDate:"2022-02-20",
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:7,
        type:"GoToWork",
        idUser:5,
        name:"นาย ญาณวุฒ สุขขุม",
        phoneNumber:"084-1297-5932",
        fromPlace:"ดีคอนโดระยอง",
        toPlace:"site 1",
        seats:2,
        numberOfPassenger:1,
        availableSeats:1,
        startDate:new Date(),
        endDate:new Date(),
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
    {
        id:8,
        type:"ComeBackHome",
        idUser:5,
        name:"นาย ญาณวุฒ สุขขุม",
        phoneNumber:"084-1297-5932",
        fromPlace:"site 7",
        toPlace:"ดีคอนโดระยอง",
        seats:3,
        numberOfPassenger:1,
        availableSeats:2,
        startDate:new Date(),
        endDate:new Date(),
        time:new Date(),
        detail:"",
        createDate:"2022-01-10"
    },
];

module.exports = RegisterOfDriver;
