const Users = [
  {
    id: 1,
    username: "admin",
    email: "admin@scg.com",
    password: "adminadmin",
    image: "1.jpg",
    firstname: "Tapmid",
    lastname: "Humphries",
    fNameThai:"Tapmid Humphries",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Assistant Manager-HR Business Partner",
    mobileNumber: "065-556-3915",
    workingLocation: "TPE - Rayong Site#1",
    site: 1,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER", "ROLE_ADMIN"],
    lat:12.679434938663885,
    long:101.17404131169592,
    address: "44/112 ซ.ศักดิ์ทิพย์8 ถ.กรอกยายชา ต.เนินพระ อ.เมือง จ.ระยอง 21150",
    addressNumber:"44/112",
    villageSoi:"ศักดิ์ทิพย์8",
    streetRoad:"กรอกยายชา",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21150",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 2,
    username: "manager",
    email: "manager@scg.com",
    password: "managermanager",
    image: "2.jpg",
    firstname: "Theodor",
    lastname: "O'Moore",
    fNameThai:"Theodor O'Moore",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Manager-HR Business Partner",
    mobileNumber: "085-550-0949",
    workingLocation: "TPE - Rayong Site#1",
    site: 1,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER", "ROLE_MANAGER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 3,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "3.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    fNameThai:"Shaunna Richard",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-558-9673",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.72518242027518,
    long:101.22013902425918,
    address: "69/8 ซ.หมู่ 8 บ้านสะพานหิน-เขาโบสถ์ ต.ทับมา อ.เมือง จ.ระยอง 21000",
    addressNumber:"69/8",
    villageSoi:"หมู่ 8 บ้านสะพานหิน-เขาโบสถ์",
    streetRoad:"-",
    subdistrictTambol:"ทับมา",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 4,
    username: "Welldriver",
    email: "welldriver@domain.com",
    password: "welldriver12",
    image: "2.jpg",
    firstname: "Kim",
    lastname: "HyeJin",
    fNameThai:"Kim HyeJin",
    idDepartment: 2,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "082-541-1254",
    workingLocation: "TPE - Rayong Site#3",
    site: 7,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER","ROLE_DRIVER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 5,
    username: "alaynawo",
    email: "alaynawo@domain.com",
    password: "useruser",
    image: "5.jpg",
    firstname: "Alayna",
    lastname: "Wolfe",
    fNameThai:"Alayna Wolfe",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control",
    position: "Quality Control Technician - PAL",
    mobileNumber: "085-558-4021",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 6,
    username: "anishava",
    email: "anishava@domain.com",
    password: "useruser",
    image: "6.jpg",
    firstname: "Anisha",
    lastname: "Valdez",
    fNameThai:"Anisha Valdez",
    idDepartment: 12,
    department: "Safety, Occupational Health & Environment",
    position: "Occupational Health & Safety System Engineer",
    mobileNumber: "085-555-6279",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.695161966150467,
    long:101.31651283724382,
    address: "19/21 ซ.หมู่1/หมูบ้านสกาย วิลล์ / ซอย 4. ถ.ชากใหญ่-บ้านแลง ต.นาตาขวัญ อ.เมือง จ.ระยอง 2100",
    addressNumber:"49/72",
    villageSoi:"หมู่1/หมูบ้านสกาย วิลล์ / ซอย 4.",
    streetRoad:"ชากใหญ่-บ้านแลง",
    subdistrictTambol:"นาตาขวัญ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 7,
    username: "aedankn",
    email: "aedankn@domain.com",
    password: "useruser",
    image: "7.jpg",
    firstname: "Aedan",
    lastname: "Knights",
    fNameThai:"Aedan Knights",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-554-4538",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 8,
    username: "kaitlabr",
    email: "kaitlabr@domain.com",
    password: "useruser",
    image: "8.jpg",
    firstname: "Kaitlan",
    lastname: "Braun",
    fNameThai:"Kaitlan Braun",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-559-9269",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 9,
    username: "krystich",
    email: "krystich@domain.com",
    password: "useruser",
    image: "9.jpg",
    firstname: "Krystian",
    lastname: "Chase",
    fNameThai:"Krystian Chase",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-9798",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4,
    pointLentCar:4.5,
  },
  {
    id: 10,
    username: "wilburro",
    email: "wilburro@domain.com",
    password: "useruser",
    image: "10.jpg",
    firstname: "Wilbur",
    lastname: "Roberts",
    fNameThai:"Wilbur Roberts",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-557-2907",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 11,
    username: "maciema",
    email: "maciema@domain.com",
    password: "useruser",
    image: "11.jpg",
    firstname: "Macie",
    lastname: "Marshall",
    fNameThai:"Macie Marshall",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-554-0195",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 12,
    username: "amiecr",
    email: "amiecr@domain.com",
    password: "useruser",
    image: "12.jpg",
    firstname: "Amie",
    lastname: "Croft",
    fNameThai:"Amie Croft",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-556-3474",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 13,
    username: "keeganba",
    email: "keeganba@domain.com",
    password: "useruser",
    image: "13.jpg",
    firstname: "Keegan",
    lastname: "Bates",
    fNameThai:"Keegan Bates",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-555-0867",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 14,
    username: "roisinmi",
    email: "roisinmi@domain.com",
    password: "useruser",
    image: "14.jpg",
    firstname: "Roisin",
    lastname: "Millington",
    fNameThai:"Roisin Millington",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-555-7752",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 15,
    username: "elenibi",
    email: "elenibi@domain.com",
    password: "useruser",
    image: "15.jpg",
    firstname: "Eleni",
    lastname: "Bishop",
    fNameThai:"Eleni Bishop",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-552-2903",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.706381266331915,
    long:100.99428168998405,
    address: "51/46 ซ.ม.4 ต.สำนักท้อน อ.บ้านฉาง จ.ระยอง 21130",
    addressNumber:"51/46",
    villageSoi:"ม.4",
    streetRoad:"-",
    subdistrictTambol:"สำนักท้อน",
    district:"บ้านฉาง",
    province:"ระยอง",
    postalCode:"21130",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 16,
    username: "rajfr",
    email: "rajfr@domain.com",
    password: "useruser",
    image: "16.jpg",
    firstname: "Raj",
    lastname: "Fraser",
    fNameThai:"Raj Fraser",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-5467",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 17,
    username: "dottybo",
    email: "dottybo@domain.com",
    password: "useruser",
    image: "17.jpg",
    firstname: "Dotty",
    lastname: "Bowers",
    fNameThai:"Dotty Bowers",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-553-1111",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 18,
    username: "saeedal",
    email: "saeedal@domain.com",
    password: "useruser",
    image: "18.jpg",
    firstname: "Saeed",
    lastname: "Alvarado",
    fNameThai:"Saeed Alvarado",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-555-7759",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 19,
    username: "gurleele",
    email: "gurleele@domain.com",
    password: "useruser",
    image: "19.jpg",
    firstname: "Gurleen",
    lastname: "Leon",
    fNameThai:"Gurleen Leon",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-556-3139",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 20,
    username: "adrianca",
    email: "adrianca@domain.com",
    password: "useruser",
    image: "20.jpg",
    firstname: "Adrianna",
    lastname: "Campos",
    fNameThai:"Adrianna Campos",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-552-3709",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 21,
    username: "enyapi",
    email: "enyapi@domain.com",
    password: "useruser",
    image: "21.jpg",
    firstname: "Enya",
    lastname: "Pittman",
    fNameThai:"Enya Pittman",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-558-6568",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 22,
    username: "keithva",
    email: "keithva@domain.com",
    password: "useruser",
    image: "22.jpg",
    firstname: "Keith",
    lastname: "Vazquez",
    fNameThai:"Keith Vazquez",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-551-9891",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 23,
    username: "arjunco",
    email: "arjunco@domain.com",
    password: "useruser",
    image: "23.jpg",
    firstname: "Arjun",
    lastname: "Connolly",
    fNameThai:"Arjun Connolly",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-559-8630",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 24,
    username: "michalki",
    email: "michalki@domain.com",
    password: "useruser",
    image: "24.jpg",
    firstname: "Michalina",
    lastname: "King",
    fNameThai:"Michalina King",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-550-3437",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 25,
    username: "mathilbo",
    email: "mathilbo@domain.com",
    password: "useruser",
    image: "25.jpg",
    firstname: "Mathilda",
    lastname: "Bonilla",
    fNameThai:"Mathilda Bonilla",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "095-551-9585",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 26,
    username: "kerysrh",
    email: "kerysrh@domain.com",
    password: "useruser",
    image: "26.jpg",
    firstname: "Kerys",
    lastname: "Rhodes",
    fNameThai:"Kerys Rhodes",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-551-4975",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 27,
    username: "bartosse",
    email: "bartosse@domain.com",
    password: "useruser",
    image: "27.jpg",
    firstname: "Bartosz",
    lastname: "Sexton",
    fNameThai:"Bartosz Sexton",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-557-7282",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.7078927,
    long:101.2029732,
    address: "18/153 ซ.บุญถาวรถ5 ถ.โขดหิน-เขาไผ่ ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"18/153",
    villageSoi:"บุญถาวรถ5",
    streetRoad:"โขดหิน-เขาไผ่",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 28,
    username: "annmarkl",
    email: "annmarkl@domain.com",
    password: "useruser",
    image: "28.jpg",
    firstname: "Ann-Marie",
    lastname: "Klein",
    fNameThai:"Ann-Marie Klein",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "065-553-2502",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 29,
    username: "kajolwh",
    email: "kajolwh@domain.com",
    password: "useruser",
    image: "29.jpg",
    firstname: "Kajol",
    lastname: "Whittington",
    fNameThai:"Kajol Whittington",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control",
    position: "Quality Assurance & Quality Control Department",
    mobileNumber: "085-558-0153",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 30,
    username: "evelynst",
    email: "evelynst@domain.com",
    password: "useruser",
    image: "30.jpg",
    firstname: "Evelyn",
    lastname: "Stevenson",
    fNameThai:"Evelyn Stevenson",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-551-7861",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "terminate",
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 31,
    username: "driver",
    email: "driver@domain.com",
    password: "driverdriver",
    image: "30.jpg",
    firstname: "Tom",
    lastname: "John",
    fNameThai:"Tom John",
    idDepartment: 6,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "085-551-7861",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER","ROLE_DRIVER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id: 32,
    username: "Funnydriver",
    email: "funnyDriver@domain.com",
    password: "Funnydriver12",
    image: "2.jpg",
    firstname: "Kim",
    lastname: "HyeJin",
    fNameThai:"Kim HyonU",
    idDepartment: 2,
    department: "HDPE 4",
    position: "HDPE 4 Production Operator",
    mobileNumber: "082-541-1254",
    workingLocation: "TPE - Rayong Site#3",
    site: 7,
    status: true,
    company: "Thai Polyethylene Co., Ltd.",
    authorities: ["ROLE_USER","ROLE_DRIVER"],
    lat:12.681514471798488,
    long:101.24158647101561,
    address: "789/449 ดีคอนโดนครระยอง ถ.สุขุมวิท ต.เนินพระ อ.เมือง จ.ระยอง 21000",
    addressNumber:"789/449",
    villageSoi:"ดีคอนโดนครระยอง",
    streetRoad:"สุขุมวิท",
    subdistrictTambol:"เนินพระ",
    district:"เมือง",
    province:"ระยอง",
    postalCode:"21000",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
    id:2036,
    scgEmployeeId:"0100-000680",
    prename:"นาย",
    fNameThai: "สุวัฒ ป้อมภา",
    username:"krystich",
    email: "krystich@domain.com",
    password:"Krystich1",
    authorities:["ROLE_USER"],
    mobileNumber: "085-550-0949",
    position: "Assistant Manager-HR",
    department: "HR Business Partner",
    departmentShortName: "HRBP",
    workingLocation: "TPE",
    companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
    addressNumber:"12",
    villageSoi:"",
    streetRoad:"เอกมัย",
    subdistrictTambol:"คลองเตย",
    district:"คลองเตย",
    province:"กรุงเทพมหานคร",
    postalCode:"10150",
    lat:12.681240612897026,
    long:101.22069543253524,
    status:0,
    image:"1.jpg",
    pointFriendToFriend:4.5,
    pointLentCar:4.5,
  },
  {
      id:2044,
      scgEmployeeId:"0100-001064",
      prename:"นาย",
      fNameThai: "สมบูรณ์ ไทยญานุสร",
      username:"somboon",
      email: "krystich@domain.com",
      password:"Somboon1",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.780292135351459,
      long:101.19022439116034,
      status:1,
      image:"2.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2073,
      scgEmployeeId:"0100-001605",
      prename:"นาย",
      fNameThai: "ศักดิ์ชัย หุมสิน",
      username:"Sakchai12",
      email: "krystich@domain.com",
      password:"Sakchai12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.682209355620243,
      long:101.24201258509072,
      status:1,
      image:"3.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2079,
      scgEmployeeId:"0100-001415",
      prename:"นาย",
      fNameThai: "ศักดิ์ชัย หุมสิม",
      username:"Sakchai34",
      email: "krystich@domain.com",
      password:"Sakchai34",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.716237833669975,
      long:101.30725134245453,
      status:0,
      image:"4.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2090,
      scgEmployeeId:"0100-001571",
      prename:"นาย",
      fNameThai: "ภูมิมินทร์ ใจหาญ",
      username:"Poomminchai",
      email: "krystich@domain.com",
      password:"Poomminchai12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.6868052,
      long:101.2651274,
      status:0,
      image:"5.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2092,
      scgEmployeeId:"0100-001374",
      prename:"นาย",
      fNameThai: "สัมฤทธิ์ คำสงค์",
      username:"SomlidKomSong",
      email: "krystich@domain.com",
      password:"SomlidKomSong12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.767028760158432,
      long:101.17723029020047,
      status:0,
      image:"6.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2099,
      scgEmployeeId:"0100-000960",
      prename:"นาย",
      fNameThai: "ชูชาติ รัตนเพ็ชร",
      username:"SushatRut",
      email: "chuchara@scg.com",
      password:"SushatRut12",
      authorities:["ROLE_USER"],
      mobileNumber: "0890589785",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE - Rayong Site#1",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"19/21",
      villageSoi:"หมู่1/หมูบ้านสกาย วิลล์ / ซอย 4.",
      streetRoad:"ชากใหญ่-บ้านแลง",
      subdistrictTambol:"นาตาขวัญ",
      district:"เมือง",
      province:"ระยอง",
      postalCode:"21000",
      lat:12.695161966150467,
      long:101.31651283724382,
      status:0,
      image:"7.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2114,
      scgEmployeeId:"0100-001540",
      prename:"นาย",
      fNameThai: "สัมฤทธิ์ คำสง",
      username:"Somlid56",
      email: "krystich@domain.com",
      password:"Somlid56",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.712475559716722,
      long:101.21318225570424,
      status:0,
      image:"8.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2118,
      scgEmployeeId:"0100-001478",
      prename:"นาย",
      fNameThai: "อภิวัฒน์ นิคมเขตต์",
      username:"ApiwatNikom",
      email: "apiwatni@scg.com",
      password:"ApiwatNikom12",
      authorities:["ROLE_USER"],
      mobileNumber: "0851019031",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE - Rayong Site#1",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"69/8",
      villageSoi:"หมู่ 8 บ้านสะพานหิน-เขาโบสถ์",
      streetRoad:"-",
      subdistrictTambol:"ทับมา",
      district:"เมือง",
      province:"ระยอง",
      postalCode:"21000",
      lat:12.72518242027518,
      long:101.22013902425918,
      status:0,
      image:"9.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2145,
      scgEmployeeId:"0100-001257",
      prename:"นาย",
      fNameThai: "ณัฐพล พรพิทยากุล",
      username:"Natthapon",
      email: "krystich@domain.com",
      password:"Natthapon12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.712218399999999,
      long:101.32196980000001,
      status:0,
      image:"10.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2148,
      scgEmployeeId:"0100-001775",
      prename:"นาย",
      fNameThai: "ภานุวัฒน์ แก้ววงศ์",
      username:"PanuwatKaew",
      email: "krystich@domain.com",
      password:"PanuwatKaew12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.6736612,
      long:101.27238060000001,
      status:0,
      image:"11.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2167,
      scgEmployeeId:"0100-001572",
      prename:"นาย",
      fNameThai: "ณัฐพล พรพิทยากุน",
      username:"Nutthapon12",
      email: "krystich@domain.com",
      password:"Nutthapon12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.679503591987821,
      long:101.27955072364304,
      status:0,
      image:"12.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2168,
      scgEmployeeId:"0100-001791",
      prename:"นาย",
      fNameThai: "ภานุวัฒน์ แก้ววงษ์",
      username:"Panuwat12",
      email: "krystich@domain.com",
      password:"Panuwat12",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.676568561067688,
      long:101.26440310014563,
      status:0,
      image:"13.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2180,
      scgEmployeeId:"0100-001133",
      prename:"นาย",
      fNameThai: "ชนาธิป สรรพวิเศษ",
      username:"Chanathip2",
      email: "krystich@domain.com",
      password:"Chanathip2",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.709720017704441,
      long:101.21109330649875,
      status:0,
      image:"14.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2188,
      scgEmployeeId:"2220-000019",
      prename:"นาย",
      fNameThai: "สนิท แต่งตั้ง",
      username:"SanitSanit",
      email: "krystich@domain.com",
      password:"SanitSanit",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.696188862837351,
      long:101.21798775039829,
      status:0,
      image:"15.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2190,
      scgEmployeeId:"0100-001381",
      prename:"นาย",
      fNameThai: "จีรศักดิ์ ประสพสุข",
      username:"JirasakPasob",
      email: "krystich@domain.com",
      password:"JirasakPasob1",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.766356102876506,
      long:101.17707017835976,
      status:0,
      image:"16.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2191,
      scgEmployeeId:"2220-000034",
      prename:"นาย",
      fNameThai: "จีรศักดิ์ ประสบสุข",
      username:"JirasakPasob2",
      email: "krystich@domain.com",
      password:"JirasakPasob2",
      authorities:["ROLE_USER"],
      mobileNumber: "085-550-0949",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"12",
      villageSoi:"",
      streetRoad:"เอกมัย",
      subdistrictTambol:"คลองเตย",
      district:"คลองเตย",
      province:"กรุงเทพมหานคร",
      postalCode:"10150",
      lat:12.847289731643839,
      long:101.19282620433572,
      status:0,
      image:"17.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
  {
      id:2213,
      scgEmployeeId:"0100-001154",
      prename:"นาง",
      fNameThai: "จิรพันธ์ สุวรรณทวี",
      username:"JiraPan1",
      email: "jirapans@scg.com",
      password:"JiraPan1",
      authorities:["ROLE_USER"],
      mobileNumber: "0849660533",
      position: "Assistant Manager-HR",
      department: "HR Business Partner",
      departmentShortName: "HRBP",
      workingLocation: "TPE - Rayong Site#1",
      companyNameTH:"บริษัท ไทยโพลิเอททีลีน จำกัด",
      addressNumber:"44/112",
      villageSoi:"ศักดิ์ทิพย์8",
      streetRoad:"กรอกยายชา",
      subdistrictTambol:"เนินพระ",
      district:"เมือง",
      province:"ระยอง",
      postalCode:"21150",
      lat:12.679434938663885,
      long:101.17404131169592,
      status:0,
      image:"18.jpg",
      pointFriendToFriend:4.5,
      pointLentCar:4.5,
  },
];
module.exports = Users;
