const VehicleBrandsAndModels = [
    {
        id:1,
        idType:2,
        brand:"Suzuki",
        model: "Suzuki Celerio",
        motor: "998 cc",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        imagepath: "car1.png",
    },
    {
        id:2,
        idType:2,
        brand: "Nissan",
        model: "Nissan March",
        motor: "1,198 cc, 79 แรงม้า(PS)",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน(95,91,E20), แก๊สโซฮอล์(95,91)",
        breakABS: "มี",
        capacity: 4,
        imagepath: "car3.jpg",
    },
    {
        id:3,
        idType:2,
        brand: "Honda",
        model: "Honda Brio",
        motor: "1,200 cc",
        gear: "เกียร์ออโต้",
        gas: "เบนซิน",
        breakABS: "มี",
        capacity: 4,
        imagepath: "car5.jpg",
    },
    {
        id:4,
        idType:3,
        brand: "Toyota",
        model: "Toyota Hilux Revo 2017",
        motor: "2,393 cc, 150 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "มี",
        capacity: 6,
        imagepath: "car2.png",
    },
    {
        id:5,
        idType:3,
        brand: "Mazda",
        model: "Mazda BT-50 Double Cab",
        motor: "3,600 cc, 150 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล B20",
        breakABS: "มี",
        capacity: 6,
        imagepath: "car6.jpeg",
    },
    {
        id:6,
        idType:1,
        brand: "Nissan",
        model: "Nissan Urvan",
        motor: "2,488 cc, 129 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล, ไบโอดีเซล B5",
        breakABS: "ไม่มี",
        capacity: 6,
        imagepath: "car4.jpg",
    },
    {
        id:7,
        idType:1,
        brand: "Toyota",
        model: "Toyota Commuter 2.8 MT",
        motor: "2,755 cc, 163 แรงม้า(PS)",
        gear: "เกียร์กระปุก",
        gas: "ดีเซล 2.8 MT",
        breakABS: "มี",
        capacity: 6,
        imagepath: "car7.jpeg",
    },
    {
        id:8,
        idType:4,
        brand: "Mercedes Benz",
        model: "Mercedes Benz Sprinter 416 CDI Business 2019",
        motor: "2,987 cc, 190 แรงม้า(HP)",
        gear: "เกียร์ออร์โต้",
        gas: "ดีเซล",
        breakABS: "มี",
        capacity: 6,
        imagepath: "car8.jpeg",
    },
];

module.exports = VehicleBrandsAndModels;